# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wander Far
tagline:             'Not all those who wander are lost'
description:         'A blog to accompany the photos at <a href="http://wanderfar.co.uk" target="_blank">Wander Far</a>.'
url:                 http://wanderfar.co.uk
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Andrew Chong
  url:               http://wanderfar.co.uk
  email:             andrew.chong@tesco.net

# Custom vars
version:             1.0.0
